-- OBSOLETO: este archivo antes creaba políticas FOR ALL USING (true), que anulaban RLS.
-- No lo ejecutes. Usa scripts/security_hardening_2026.sql, que deja la sincronización
-- en el servidor con SUPABASE_SERVICE_ROLE_KEY y conserva RLS para clientes públicos.
