-- ============================================================================
-- SEED P1 -> P2: PUBLICACIONES DESCUBIERTAS REALES DE YOUTUBE E INSTAGRAM
-- Proyecto: Banda Bruna
-- show_on_web = false, web_order = null (separación editorial estricta)
-- ============================================================================

INSERT INTO public.social_posts (
  platform, external_id, url, post_type, title, caption, thumbnail_url,
  thumbnail_is_ephemeral, published_at, likes, views, comments, disponible, show_on_web, web_order
) VALUES
  ('youtube', 'fNyxHeMzJTI', 'https://www.youtube.com/shorts/fNyxHeMzJTI', 'short', 'Luna Amiga -  Video en la Playa', 'Luna Amiga guarda este secreto, nuestro amigos Cris y Cami, bailan este éxito de Banda Bruna, tu igual nos puedes enviar tu video!', 'https://i3.ytimg.com/vi/fNyxHeMzJTI/hqdefault.jpg', false, '2026-08-26T15:50:39.000Z', 22, 951, NULL, true, false, NULL),
  ('youtube', 'gmXPa4HyRfs', 'https://www.youtube.com/shorts/gmXPa4HyRfs', 'short', 'FUIMOS ENGAÑADOS', 'Nos preguntaron con quien te llevas mejor en la Banda Bruna, cuando salen a sus eventos... y bueno algo paso en la edición que todo cambio!!   #humor #comedia #parati #musicos #amigos #bandabruna', 'https://i4.ytimg.com/vi/gmXPa4HyRfs/hqdefault.jpg', false, '2026-08-13T14:28:58.000Z', 19, 1377, NULL, true, false, NULL),
  ('youtube', '0Zrx62mRARw', 'https://www.youtube.com/watch?v=0Zrx62mRARw', 'video', 'Homenaje Al Minero', 'Mientras ensayamos recordamos este tremendo clásico y quisimos tocarlo para saludar a todos los mineros y mineras de nuestro país!', 'https://i1.ytimg.com/vi/0Zrx62mRARw/hqdefault.jpg', false, '2026-08-13T14:23:47.000Z', 4, 29, NULL, true, false, NULL),
  ('youtube', 'FoM7u1xDlIs', 'https://www.youtube.com/shorts/FoM7u1xDlIs', 'short', 'RESUMEN EVENTO EXPO MUNDO FAMILIA TEMUCO', 'ESTE FIN DE SEMANA PARTICIPAMOS COMO ARTISTAS INVITADOS A ESTE GRAN EVENTO FAMILIAR, REALMENTE UN LUJO. TE INVITAMOS A VER LAS IMPRESIONES.', 'https://i3.ytimg.com/vi/FoM7u1xDlIs/hqdefault.jpg', false, '2026-08-13T14:08:30.000Z', 4, 41, NULL, true, false, NULL),
  ('youtube', 'mZhYl60ENAs', 'https://www.youtube.com/watch?v=mZhYl60ENAs', 'video', 'Banda Bruna - Ahogado en un Bar (Videoclip Oficial)', '🎵 BANDA BRUNA - AHOGADO EN UN BAR (Videoclip Oficial)  🎬 PRODUCCIÓN AUDIOVISUAL AgenciaCK.cl  Dirección General: Jorge Villagrán  🎤 INTEGRANTES  César Bruna Díaz – Voz Principal Vicente Daniel Núñez Marchant – Guitarra y Arreglos Musicales Gerson Eduardo Ulloa Canio – Bajo Jaime Esteban Cárdenas Quilodrán – Batería Jaime Fabián Cárdenas Sanhueza – Congas Fabián Ignacio Garrido Espinoza – Güira Israel Andrés Lagos Rocha – Teclados  Samuel Andrés Vega Gallegos – Sonido, Mezcla y Masterización (ZPX Studio)  ✍ Autor y Compositor Jaime Fabián Cárdenas Sanhueza  🎭 ELENCO Alejandro Stefanini Melva Ruiz  ⭐ Participación Especial Katy Sandoval Paola Ríos Paola Gelvez Neira Andrea Matus Laura Quilodrán   Segunda Cámara: Sebastián Ríos Parada  Edición y Montaje: AgenciaCK.cl  🚁 DRONE Sebastián Ríos Parada Gabriel Rifo Jérez  🎧 PRODUCCIÓN MUSICAL Grabación: ZPX Studio  Mezcla y Masterización: Samuel Andrés Vega Gallegos  📍 LOCACIONES Cervecería Maquehue Centro de Eventos Araucaria  🙏 AGRADECIMIENTOS A todas las personas que hicieron posible la realización de este videoclip.  © Banda Bruna Todos los derechos reservados.', 'https://i2.ytimg.com/vi/mZhYl60ENAs/hqdefault.jpg', false, '2026-07-04T23:00:06.000Z', 239, 26243, NULL, true, false, NULL),
  ('youtube', 'g1_xEf8rrrQ', 'https://www.youtube.com/shorts/g1_xEf8rrrQ', 'short', 'Próximamente en todas nuestras plataformas...! #cumbia #chile #fyp #viral', NULL, 'https://i4.ytimg.com/vi/g1_xEf8rrrQ/hqdefault.jpg', false, '2026-06-28T20:17:25.000Z', 5, 201, NULL, true, false, NULL),
  ('youtube', 'CyzaRn03rXw', 'https://www.youtube.com/shorts/CyzaRn03rXw', 'short', 'esto es solo un adelanto de lo nuevo que se viene! #araucania #musica #cumbia #baile #envivo', NULL, 'https://i4.ytimg.com/vi/CyzaRn03rXw/hqdefault.jpg', false, '2026-06-19T01:19:30.000Z', 9, 415, NULL, true, false, NULL),
  ('youtube', 'KmxvhAyz8Zg', 'https://www.youtube.com/shorts/KmxvhAyz8Zg', 'short', 'ADELANTO DE NUESTRO PRÓXIMO VIDEO CLIP', 'PRONTO ESTARÁ DISPONIBLE EL VIDEO DE NUESTRO PROXIMO TEMA: AHOGADO EN UN BAR... NO TE LO PIERDAS', 'https://i4.ytimg.com/vi/KmxvhAyz8Zg/hqdefault.jpg', false, '2026-06-15T17:51:04.000Z', 18, 1521, NULL, true, false, NULL),
  ('youtube', 'Xr5GbRXl__Y', 'https://www.youtube.com/shorts/Xr5GbRXl__Y', 'short', 'DÍA DE LA MADRE - BANDA BRUNA - FREIRE 2026 #cumbia #musica #personasmayores  #mujeres  #araucania', 'Resumen de nuestra presentación en la celebración día de la madre, en Freire, Región de la Araucanía,  donde realizamos un show con éxitos del ayer y finalizamos con toda la pachanga, full bailable, para todas las mamitas en su día!  si tu quieres que animemos tu evento no dudes en contactarnos.  síguenos en redes sociales, suscríbete y no dudes dejarnos un comentario... casi lo olvido! para mayor información visítanos en www.bandabruna.cl', 'https://i1.ytimg.com/vi/Xr5GbRXl__Y/hqdefault.jpg', false, '2026-05-13T20:16:49.000Z', 7, 292, NULL, true, false, NULL),
  ('youtube', 'POhyzSspP0Y', 'https://www.youtube.com/shorts/POhyzSspP0Y', 'short', 'VERANO 2026', 'Tras una intensa temporada recorriendo diversos escenarios y compartiendo nuestra música, donde tuvimos la oportunidad de presentarnos en las regiones de Biobío, La Araucanía y Los Ríos.   Queremos agradecer profundamente a cada persona que nos brindó su cariño, ya sea con un aplauso o simplemente disfrutando con nosotros. Nuestra gratitud también para los productores y municipalidades que confiaron en el talento de Banda Bruna.  ¡Esto no termina aquí! En los próximos meses seguiremos realizando shows y trabajando en nuevos temas y sorpresas. Los invitamos a seguir conectados en nuestras redes sociales para no perderse lo que viene. .', 'https://i1.ytimg.com/vi/POhyzSspP0Y/hqdefault.jpg', false, '2026-03-06T12:03:58.000Z', 8, 355, NULL, true, false, NULL),
  ('youtube', 'XxFJzWSCGJk', 'https://www.youtube.com/watch?v=XxFJzWSCGJk', 'video', 'Banda Bruna - Mix Exitos De Los Vikings 5 (Show Adulto Mayor)', 'Les compartimos este recuerdo especial de nuestra presentación en el Primer Encuentro Comunal de Personas Mayores Toltén 2025, donde revivimos los éxitos de cumbia que han marcado generaciones. Fue una tarde mágica, llena de baile y alegría, y quisimos capturarla para que la vivan con nosotros. Esperamos que este video los transporte a esos momentos de fiesta inolvidables. ¡Gracias por acompañarnos! #musica Cumbia #CumbiaClásica #Concierto #MúsicaEnVivo #FinDeAño #FiestaFinDeAño #BandaDeCumbia #Recuerdos #MúsicaRetro #ÉxitosDeCumbia #BandaBruna #tolten', 'https://i1.ytimg.com/vi/XxFJzWSCGJk/hqdefault.jpg', false, '2025-09-25T12:29:03.000Z', 41, 3384, NULL, true, false, NULL),
  ('youtube', 'Lw7QBeyp9f0', 'https://www.youtube.com/watch?v=Lw7QBeyp9f0', 'video', 'Banda Bruna - Mix Cumbias Clásicas (Show Adulto Mayor)', 'Disfruta de esta intensa presentación en vivo de Banda Bruna interpretando "Mix de Cumbias Clásicas" ", una muestra auténtica del sonido y la fuerza que caracteriza a la agrupación.  🎸 Grabado en La Comuna de Toltén, y que es un extracto del Show Nueva Ola presentado en la celebración del adulto mayor en la comuna, en marco de las actividades de la Municipalidad de Toltén.   🔔 ¡Suscríbete para más lanzamientos y contenido exclusivo! 📲 Síguenos en redes sociales: Instagram:   / banda_bruna/ Facebook:   / bandabrunaoficial/ TikTok: @bandabrunaoficial Spotify: @bandabruna', 'https://i1.ytimg.com/vi/Lw7QBeyp9f0/hqdefault.jpg', false, '2025-09-24T13:22:29.000Z', 25, 1510, NULL, true, false, NULL),
  ('youtube', 'p_zdcQEEOFY', 'https://www.youtube.com/watch?v=p_zdcQEEOFY', 'video', 'Banda Bruna - Agonía (Sesión En Vivo)', 'Disfruta de esta intensa presentación en vivo de Banda Bruna interpretando su tema "Agonía", una muestra auténtica del sonido y la fuerza que caracteriza a la agrupación.  🎸 Grabado en una sesión especial pensada para resaltar la energía cruda del directo, esta versión en vivo te sumerge en la esencia de la banda.  🔔 ¡Suscríbete para más sesiones en vivo, lanzamientos y contenido exclusivo! 📲 Síguenos en redes sociales: Instagram:   / banda_bruna/ Facebook:   / bandabrunaoficial/ TikTok: @bandabrunaoficial Spotify: @bandabruna  #BandaBruna #Agonía #EnVivo #MúsicaChilena  #SesiónEnVivo', 'https://i1.ytimg.com/vi/p_zdcQEEOFY/hqdefault.jpg', false, '2025-08-22T00:00:06.000Z', 22, 688, NULL, true, false, NULL),
  ('youtube', '_xLejMEc3wg', 'https://www.youtube.com/shorts/_xLejMEc3wg', 'short', 'Como dejar de amarte', 'Nos pidieron este tema para una fiesta privada, pero creo que lo vamos a incluir en el repertorio de fiestas patrias!', 'https://i4.ytimg.com/vi/_xLejMEc3wg/hqdefault.jpg', false, '2025-08-18T13:07:40.000Z', 8, 99, NULL, true, false, NULL),
  ('youtube', 'xMAajydQ8ZQ', 'https://www.youtube.com/watch?v=xMAajydQ8ZQ', 'video', 'Banda Bruna - Mix Nueva Ola (Sesión En Vivo)', '¡Vive la fuerza del directo con Banda Bruna! En esta presentación grabada en una sesión exclusiva, la banda interpreta una intensa selección de canciones inspiradas en la Nueva Ola, reviviendo el espíritu rebelde y nostálgico de una época dorada, pero con un enfoque contemporáneo y lleno de actitud.  Esta sesión en vivo no es solo una muestra musical: es una experiencia cruda, honesta y vibrante. Desde las guitarras envolventes hasta las letras cargadas de emoción, Banda Bruna entrega una interpretación que conecta directamente con el público, manteniéndose fiel a su esencia sonora y al fuerte vínculo con sus raíces musicales. Grabado con dedicación y pasión, este material busca rescatar el valor de la música en vivo como forma de expresión directa, sin artificios, donde lo importante es la conexión real entre músicos y audiencia.  🔔 ¡Suscríbete a nuestro canal para no perderte las próximas sesiones en vivo, estrenos y contenido exclusivo directamente desde el corazón de Banda Bruna!  📲 Síguenos y comparte la música: Instagram: @banda_bruna Facebook: Banda Bruna Oficial TikTok: @bandabrunaoficial Spotify: Banda Bruna  #BandaBruna #NuevaOla #RockAlternativo #RockChileno #MúsicaChilena #RockEnEspañol #MúsicaIndependiente', 'https://i1.ytimg.com/vi/xMAajydQ8ZQ/hqdefault.jpg', false, '2025-08-15T18:49:41.000Z', 58, 1698, NULL, true, false, NULL),
  ('instagram', 'DZ2tTR7OSFX', 'https://www.instagram.com/p/DZ2tTR7OSFX/', 'post', NULL, 'No dudes en comunicarte con nosotros! Agenda abierta para estas fiestas patrias! #chile #fiestaspatriaschile #temuco', 'https://scontent.cdninstagram.com/v/t51.82787-15/729561482_17969932785082499_6497969336669463398_n.webp', true, '2026-06-21T04:00:00.000Z', 26, NULL, 0, true, false, NULL)
ON CONFLICT (platform, external_id) DO NOTHING;
